### ISSUE TITLE
Request for App: Name Auto-renewal App

### ISSUE THREAD

**Issue by jcnelson** [blockstack/sample-apps#3]
It would be nice to have a desktop tool that could periodically run `blockstack whois` to see which of your names need to be renewed.  If a name is getting close to expiration, the tool should let the user know so they can run `blockstack renew` (e.g. via desktop notification, via email, via SMS, whatever).

A slightly more advanced version would automatically renew the name.

This is an interesting problem, because renewal can't be put off until the last second (lest your transaction get stuck in a backlog for example).  I personally would do my renewal no less than a month in advance.

**Comment by dsmurrell** [comment]
Funny that :)

<img width="710" alt="screen shot 2017-02-10 at 21 16 40" src="https://cloud.githubusercontent.com/assets/4035854/22844472/59c4afce-efd6-11e6-96d7-6ac0157ca8b5.png">

I was thinking of working on something like this for the hackathon.

**Comment by pstan26** [comment]
You should still do it! here is where it came up in the #engineering slack channel
![screen shot 2017-02-10 at 4 37 51 pm](https://cloud.githubusercontent.com/assets/5605552/22845175/572cfab8-efaf-11e6-8543-61b0cb611464.png)

**Comment by pstan26** [comment]
Moved this issue to https://github.com/blockstack/blockstack-apps/issues/4

**Comment by pstan26** [comment]
closing
