### ISSUE TITLE
Request for App: Software repo snapshot app

### ISSUE THREAD

**Issue by jcnelson** [blockstack/sample-apps#4]
What if there was an app where you could snapshot your source code releases in your zone files?  If your users know your blockchain ID, then they can verify that the code came from you without trusting the VCS (e.g. github).

When you want to publish a release, the app would update your name's zone file by adding a `TXT` record with the URL to the repo, along with the HEAD hash.  Then, to check out the code, the app would `git clone` the URL and verify that HEAD matches the zone file's HEAD hash.  Now, you're no longer trusting the server in the URL; you're trusting the developer.

**Comment by pstan26** [comment]
Closing this issue and moving to: https://github.com/blockstack/sample-apps/issues/4
