### ISSUE TITLE
Help Wanted: $25 BTC for PRD of decentralize Domain Exchange app

### ISSUE THREAD

**Issue by pstan26** [blockstack/sample-apps#5]
If I send someone money for a domain I want, I want to know that I'm going to get it and that a transfer has, in fact, happened to the correct address (mine). Could use multisig.

This may exist as a standalone app or an API that is used across different apps that would want this feature.

**Comment by pstan26** [comment]
This request is open to anyone in the community!

**Comment by shea256** [comment]
@pstan26 want to change the name of this repo (https://github.com/blockstack/blockstack-tutorials) to "blockstack-apps" and then move the issues there?

**Comment by pstan26** [comment]
Yes, will do.

**Comment by pstan26** [comment]
I need access to do that. No "settings" button shows up where the [instructions](https://help.github.com/articles/renaming-a-repository/) say it will
